apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace : helm
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "{{ .Values.service.name }}"
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql-container
        image: {{ .Values.postgresql.image }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.dbName }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.passwordSecret.name }}
              key: {{ .Values.postgresql.passwordSecret.key }}
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
